# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c36c1574b892009f91da1c932cc688e2995b530f45aa9b76fb54a20bcc98ceb2dd3925753ef227f17c31cfe6e9997947b8402ff9ed74f1bdd42e98261d4b624

test:
  secret_key_base: c07da60fca10ad24e3f6bcb5de6d4ffaf118cc651a06ba474d9cfc3edaedd499550b1db5942af1ae862743b02ed7ead9b801a0de92a675b790d3e78dcf546efb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
